#URL_FROM_WHICH_TO_START_SCRAPING
START_URL: https://www.aruodas.lt/butai/vilniuje/puslapis/
#AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY_FOR_LOGGING
AI_INSTRUMENTATION_KEY:

#COSMOS_DATABASE_CONFIG
DB_ENDPOINT:
DB_KEY:
DB_DATABASE_NAME:
DB_CONTAINER_NAME:
CN_PARTITION_KEY: